(define-module (GuileLox token-type))

(define-public TOKEN-LEFT-PAREN 0)
(define-public TOKEN-RIGHT-PAREN 1)
(define-public TOKEN-LEFT-BRACE 2)
(define-public TOKEN-RIGHT-BRACE 3)
(define-public TOKEN-COMMA 4)
(define-public TOKEN-DOT 5)
(define-public TOKEN-MINUS 6)
(define-public TOKEN-PLUS 7)
(define-public TOKEN-SEMICOLON 8)
(define-public TOKEN-SLASH 9)
(define-public TOKEN-STAR 10)

;; Two Char
(define-public TOKEN-BANG 11)
(define-public TOKEN-BANG-EQUAL 12)
(define-public TOKEN-EQUAL 13)
(define-public TOKEN-EQUAL-EQUAL 14)
(define-public TOKEN-GREATER 15)
(define-public TOKEN-GREATER-EQUAL 16)
(define-public TOKEN-LESS 17)
(define-public TOKEN-LESS-EQUAL 18)

;; Literals
(define-public TOKEN-IDENTIFIER 19)
(define-public TOKEN-STRING 20)
(define-public TOKEN-NUMBER 21)

;; KEYWORDS
(define-public TOKEN-AND 22)
(define-public TOKEN-CLASS 23)
(define-public TOKEN-ELSE 24)
(define-public TOKEN-FALSE 25)
(define-public TOKEN-FUN 26)
(define-public TOKEN-FOR 27)
(define-public TOKEN-IF 28)
(define-public TOKEN-NIL 29)
(define-public TOKEN-OR 30)
(define-public TOKEN-PRINT 31)
(define-public TOKEN-RETURN 32)
(define-public TOKEN-SUPER 33)
(define-public TOKEN-THIS 34)
(define-public TOKEN-TRUE 35)
(define-public TOKEN-VAR 36)
(define-public TOKEN-WHILE 37)
(define-public TOKEN-EOF 38)
(define-public TOKEN-ERROR -1)

